import {
  ArrowRight,
  ArrowUpRight,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  Clipboard,
  Clock,
  Copy,
  CreditCard,
  Download,
  Eye,
  ExternalLink,
  EyeOff,
  Facebook,
  File,
  Filter,
  Folder,
  Github,
  Globe2,
  Heart,
  HelpCircle,
  Home,
  Image,
  Instagram,
  Layout,
  Linkedin,
  Loader2,
  Mail,
  Maximize,
  Menu,
  MessageSquare,
  Minimize,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Paintbrush,
  Pencil,
  Plus,
  Quote,
  Radio,
  RefreshCcw,
  Rocket,
  Save,
  Search,
  Settings,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Sliders,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  Tablet,
  ThumbsUp,
  Trash2,
  Twitter,
  Upload,
  User,
  Users,
  View,
  Wand,
  X,
  Zap,
  Ellipsis,
} from "lucide-react"

export const Icons = {
  views: View,
  orders: ShoppingBag,
  conversion: ArrowUpRight,
  arrow: ArrowRight,
  globe: Globe2,
  // New additions
  spinner: Loader2,
  trash: Trash2,
  upload: Upload,
  pencil: Pencil,
  check: Check,
  image: Image,
  logo: File,
  close: X,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  clipboard: Clipboard,
  clock: Clock,
  copy: Copy,
  creditCard: CreditCard,
  download: Download,
  ellipsis: Ellipsis,
  externalLink: ExternalLink,
  eye: Eye,
  eyeOff: EyeOff,
  file: File,
  filter: Filter,
  folder: Folder,
  github: Github,
  heart: Heart,
  help: HelpCircle,
  home: Home,
  layout: Layout,
  linkedin: Linkedin,
  mail: Mail,
  maximize: Maximize,
  menu: Menu,
  messageSquare: MessageSquare,
  minimize: Minimize,
  monitor: Monitor,
  moon: Moon,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  paintbrush: Paintbrush,
  plus: Plus,
  radio: Radio,
  rocket: Rocket,
  save: Save,
  search: Search,
  settings: Settings,
  shield: Shield,
  shoppingCart: ShoppingCart,
  sliders: Sliders,
  smartphone: Smartphone,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  tablet: Tablet,
  thumbsUp: ThumbsUp,
  user: User,
  users: Users,
  wand: Wand,
  x: X,
  zap: Zap,
  chevronDown: ChevronDown,
  
  // Social media
  twitter: Twitter,
  facebook: Facebook,
  instagram: Instagram,
  
  // Content
  quote: Quote,
  box: Layout, // Reuse layout as box
};

export type IconKey = keyof typeof Icons; 